### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by danilolekovic** [StrategistXIV/Swift#1]
Great work! Just a heads up, the name might become problematic..

https://github.com/apple/swift

**Comment by StrategistXIV** [comment]
Hello!,

Thanks for actually watching things over here (Never thought anyone would haha). First of all!: I am fully aware of this! I thought up the name a long time ago (before Apple stole my name :( ) and since I couldn't find a better name, I am just calling it like that for now. Later on I will of course replace is by another name to avoid confusion. Maybe you have suggestions?

By the way, if you're really interested in the development of this language, I could give you some updates from time to time? Right now the repository is a bit of a mess and so are the documents.

**Comment by danilolekovic** [comment]
Thanks! :smiley:
